config/routes.rb
Rails.application.routes.draw do
  get 'travelagent/index'

  resources :payments
  resources :reservations
  resources :cruises
  resources :cabins
  resources :ships
  resources :credit_cards
  resources :addresses
  resources :customers
  root 'travelagent#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer
  belongs_to :cruise
  has_and_belongs_to_many :cabins
  has_many :payments
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_if_not_found
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
    @cruise = Cruise.find(params[:cruise_id])
    @reservation.cruise_id = @cruise.id
    @customers = Customer.all
    @cabins = Cabin.where(["ship_id = ?", @cruise.ship_id])
    @cruises=Cruise.all
  end

  # GET /reservations/1/edit
  def edit
    @customers = Customer.all
    @cruises=Cruise.all
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
       if @reservation.save
            # retrieve the cabin parameter and then add it to the reservation object
 
            cabin_id = params[:cabin]
            logger.info "cabin_id: #{cabin_id}"
            cabin_id_a = cabin_id[:cabin_id]
            logger.info "cabin_id_a: #{cabin_id_a}"
    
            cabin = Cabin.find(cabin_id_a)
            logger.info "cabin: #{cabin.id}"
         
           @reservation.cabins << cabin
           @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:customer_id, :cruise_id)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.collection_select( :customer_id, @customers, :id, :last_name ) %>
  </div>

  <div class="field">
    <%= form.label :cruise_id %>
    <%= form.text_field :cruise_id %>
  </div>
<h4>Pick a cabin</h4>
<table>
<tr>
<th>Cabin</th><th>Deck</th><th>Beds</th>
</tr>
<% for cabin in @cabins %>
<tr>
<td><%= h cabin.name%></td>
<td><%= h cabin.beds %></td>
<td><%=h cabin.deck %></td>
<td><%= radio_button('cabin', 'cabin_id', "#{cabin.id}") %></td>
</tr>

<% end %>
</table>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Cruise</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.customer.first_name+" "+reservation.customer.last_name %></td>
        <td><%= reservation.cruise.name %></td>
        <td><%= link_to 'Show', reservation, :class=>"btn btn-sm btn-primary" %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation), :class=>"btn btn-sm btn-primary" %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-sm btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path, :class=>"btn btn-lg btn-primary" %>

app/views/reservations/new.html.erb
<h1>New reservation for the <%= @cruise.name %></h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= Customer.find(@reservation.customer_id).last_name %>
</p>

<p>
  <strong>Cruise:</strong>
  <%= @reservation.cruise.name %>
</p>

<h4>These cabins are included in this reservation:</h4>
<% @reservation.cabins.each do |cabin|%>
<p> <%=cabin.name %> with
<%=cabin.beds %> beds
on deck <%=cabin.deck%> of the
<%=Ship.find(cabin.ship_id).name%>
</p> <%end%>
<p><%= link_to 'Make a payment', new_payment_path(customer_id: @reservation.customer_id, reservation_id: @reservation.id) %></p>
<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>