config/routes.rb
Rails.application.routes.draw do
  get 'travelagent/index'

  resources :payments
  resources :reservations
  resources :cruises
  resources :cabins
  resources :ships
  resources :credit_cards
  resources :addresses
  resources :customers
  root 'travelagent#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  #validates :street, :city, :postcode, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cabin.rb
class Cabin < ApplicationRecord
  belongs_to :ship
  has_and_belongs_to_many :reservations
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :customer
  validates :exp_date, :number, :name_on_card, :organisation, presence: true
  enum organisation: {
    "American Express" => "American Express",
    "Visa" => "Visa",
    "MasterCard" => "MasterCard"
  }
end

app/models/cruise.rb
class Cruise < ApplicationRecord
  belongs_to :ship
  has_many :reservations

  def self.search(term)
  if term
    where('name LIKE ?', "%#{term}%").order('id DESC')
  else
    order('id DESC') 
  end
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :address, dependent: :destroy
  has_many :credit_cards
  has_many :reservations
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :customer
  belongs_to :reservation
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer
  belongs_to :cruise
  has_and_belongs_to_many :cabins
  has_many :payments
end

app/models/ship.rb
class Ship < ApplicationRecord
  has_many :cruises
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_if_not_found
  before_action :set_ship, only: [:show, :edit, :update, :destroy]

  # GET /ships
  # GET /ships.json
  def index
    @ships = Ship.all
  end

  # GET /ships/1
  # GET /ships/1.json
  def show
  end

  # GET /ships/new
  def new
    @ship = Ship.new
  end

  # GET /ships/1/edit
  def edit
  end

  # POST /ships
  # POST /ships.json
  def create
    @ship = Ship.new(ship_params)

    respond_to do |format|
      if @ship.save
        format.html { redirect_to @ship, notice: 'Ship was successfully created.' }
        format.json { render :show, status: :created, location: @ship }
      else
        format.html { render :new }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ships/1
  # PATCH/PUT /ships/1.json
  def update
    respond_to do |format|
      if @ship.update(ship_params)
        format.html { redirect_to @ship, notice: 'Ship was successfully updated.' }
        format.json { render :show, status: :ok, location: @ship }
      else
        format.html { render :edit }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ships/1
  # DELETE /ships/1.json
  def destroy
    @ship.destroy
    respond_to do |format|
      format.html { redirect_to ships_url, notice: 'Ship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ship
      @ship = Ship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ship_params
      params.require(:ship).permit(:name, :tonnage)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cabins_helper.rb
module CabinsHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/cruises_helper.rb
module CruisesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/helpers/travelagent_helper.rb
module TravelagentHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", '/' %></li>
            <li><%= link_to "Customers",   customers_path %></li>
            <li><%= link_to "Addresses", addresses_path %></li>
            <li><%= link_to "Credit cards", credit_cards_path %></li>
            <li><%= link_to "Reservations", reservations_path %></li>
            <li><%= link_to "Cruises", cruises_path %></li>
            <li><%= link_to "Ships", ships_path %></li>
            <li><%= link_to "Cabins", cabins_path %></li>
            <li><%= link_to "Payments", payments_path %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travelagent</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render :partial=> "layouts/header" %>
    <div class="container">
    <%= yield %>
  </body>
</html>